name: Build Release APK

on:
  # কোড এডিট করলে অটোমেটিক বিল্ড হবে
  push:
    branches:
      - master
      - main
  # চাইলে ম্যানুয়ালিও রান করা যাবে
  workflow_dispatch:

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Release APK বিল্ড করা হচ্ছে (এটি কোডকে অপ্টিমাইজ এবং ফাস্ট করবে)
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # মোবাইলে ইন্সটল হওয়ার জন্য অটোমেটিক সাইন (Sign) করা হচ্ছে
      - name: Generate Keystore & Sign APK
        run: |
          keytool -genkey -v -keystore temp.keystore -storepass android -alias androidkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android"
          APK_PATH=$(find app/build/outputs/apk/release -name "*-unsigned.apk" | head -n 1)
          BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
          $BUILD_TOOLS_DIR/apksigner sign --ks temp.keystore --ks-pass pass:android --key-pass pass:android "$APK_PATH"

      # সফলভাবে বিল্ড হওয়ার পর ফাইলটি ডাউনলোডের জন্য আপলোড করা হচ্ছে
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Litube-Release-APK
          path: app/build/outputs/apk/release/*.apk
